export const LOGIN_CHANGE_FORM = 'LOGIN_CHANGE_FORM';
export const LOGIN_SET_LOGIN_STATE = 'LOGIN_SET_LOGIN_STATE';
export const LOGIN_SENDING_REQUEST = 'LOGIN_SENDING_REQUEST';
export const LOGIN_SET_ERROR_MESSAGE = 'LOGIN_SET_ERROR_MESSAGE';
